spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/mallangkongtteok
    password: '0331'
  thymeleaf:
    prefix=classpath:/templates:
    enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update

server:
  port: '8080'

