spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/mallangkongtteok
    password: '347858Kkk!'
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
#  jwt:
#    header: Authorization
#    #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
#    secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
#    token-validity-in-seconds: 86400
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /Users/bona/mcUpload
      enabled: true
      file-size-threshold: 2KB
  output:
    ansi:
      enabled: DETECT
server:
  port: '8080'
file:
  dir: /Users/bona/bonaUpload
#logging:
#  pattern:
#    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
#  level:
#    org:
#      springframework: DEBUG

#comm:
#  uploadPath: /Users/bona/mcUpload/
#file:
#  upload:
#    location: /Users/bona/mcUpload/



