spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/mallangkongtteok
    password: '347858Kkk!'
  thymeleaf:
    prefix=classpath:/templates:
    enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: create-drop
  jwt:
    header: Authorization
    #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
    secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
    token-validity-in-seconds: 86400
server:
  port: '8080'




