spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/mallangkongtteok
    password: '0324'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: create
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    cache: false
server:
  port: '8080'
